'use strict';

// tests for processor
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let processor = require('../processor/index');
processor.process({},null,function(err,data)
{
   console.log(err? 'Error:' + JSON.stringify(err): 'Success:' + JSON.stringify(data));
});
/*
let wrapped = mochaPlugin.getWrapper('processor', '/processor/index.js', 'processor');

describe('processor', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    return wrapped.run({}).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
*/